// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/fickleDude/gophemart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceServiceInterface creates a new instance of MockBalanceServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceServiceInterface {
	mock := &MockBalanceServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceServiceInterface is an autogenerated mock type for the BalanceServiceInterface type
type MockBalanceServiceInterface struct {
	mock.Mock
}

type MockBalanceServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceServiceInterface) EXPECT() *MockBalanceServiceInterface_Expecter {
	return &MockBalanceServiceInterface_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockBalanceServiceInterface
func (_mock *MockBalanceServiceInterface) GetBalance(login string) (*model.Balance, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.Balance, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.Balance); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceServiceInterface_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceServiceInterface_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - login string
func (_e *MockBalanceServiceInterface_Expecter) GetBalance(login interface{}) *MockBalanceServiceInterface_GetBalance_Call {
	return &MockBalanceServiceInterface_GetBalance_Call{Call: _e.mock.On("GetBalance", login)}
}

func (_c *MockBalanceServiceInterface_GetBalance_Call) Run(run func(login string)) *MockBalanceServiceInterface_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBalanceServiceInterface_GetBalance_Call) Return(balance *model.Balance, err error) *MockBalanceServiceInterface_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBalanceServiceInterface_GetBalance_Call) RunAndReturn(run func(login string) (*model.Balance, error)) *MockBalanceServiceInterface_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderServiceInterface creates a new instance of MockOrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderServiceInterface {
	mock := &MockOrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type MockOrderServiceInterface struct {
	mock.Mock
}

type MockOrderServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderServiceInterface) EXPECT() *MockOrderServiceInterface_Expecter {
	return &MockOrderServiceInterface_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) AddOrder(order model.Order) error {
	ret := _mock.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.Order) error); ok {
		r0 = returnFunc(order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderServiceInterface_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type MockOrderServiceInterface_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - order model.Order
func (_e *MockOrderServiceInterface_Expecter) AddOrder(order interface{}) *MockOrderServiceInterface_AddOrder_Call {
	return &MockOrderServiceInterface_AddOrder_Call{Call: _e.mock.On("AddOrder", order)}
}

func (_c *MockOrderServiceInterface_AddOrder_Call) Run(run func(order model.Order)) *MockOrderServiceInterface_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Order
		if args[0] != nil {
			arg0 = args[0].(model.Order)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_AddOrder_Call) Return(err error) *MockOrderServiceInterface_AddOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderServiceInterface_AddOrder_Call) RunAndReturn(run func(order model.Order) error) *MockOrderServiceInterface_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) GetOrder(number string) (*model.Order, error) {
	ret := _mock.Called(number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.Order, error)); ok {
		return returnFunc(number)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.Order); ok {
		r0 = returnFunc(number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServiceInterface_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderServiceInterface_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - number string
func (_e *MockOrderServiceInterface_Expecter) GetOrder(number interface{}) *MockOrderServiceInterface_GetOrder_Call {
	return &MockOrderServiceInterface_GetOrder_Call{Call: _e.mock.On("GetOrder", number)}
}

func (_c *MockOrderServiceInterface_GetOrder_Call) Run(run func(number string)) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetOrder_Call) Return(order *model.Order, err error) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderServiceInterface_GetOrder_Call) RunAndReturn(run func(number string) (*model.Order, error)) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) GetOrders(login string) ([]*model.Order, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []*model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*model.Order, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*model.Order); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServiceInterface_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderServiceInterface_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - login string
func (_e *MockOrderServiceInterface_Expecter) GetOrders(login interface{}) *MockOrderServiceInterface_GetOrders_Call {
	return &MockOrderServiceInterface_GetOrders_Call{Call: _e.mock.On("GetOrders", login)}
}

func (_c *MockOrderServiceInterface_GetOrders_Call) Run(run func(login string)) *MockOrderServiceInterface_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetOrders_Call) Return(orders []*model.Order, err error) *MockOrderServiceInterface_GetOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderServiceInterface_GetOrders_Call) RunAndReturn(run func(login string) ([]*model.Order, error)) *MockOrderServiceInterface_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateOrder provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) ValidateOrder(number string) bool {
	ret := _mock.Called(number)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOrder")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(number)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOrderServiceInterface_ValidateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateOrder'
type MockOrderServiceInterface_ValidateOrder_Call struct {
	*mock.Call
}

// ValidateOrder is a helper method to define mock.On call
//   - number string
func (_e *MockOrderServiceInterface_Expecter) ValidateOrder(number interface{}) *MockOrderServiceInterface_ValidateOrder_Call {
	return &MockOrderServiceInterface_ValidateOrder_Call{Call: _e.mock.On("ValidateOrder", number)}
}

func (_c *MockOrderServiceInterface_ValidateOrder_Call) Run(run func(number string)) *MockOrderServiceInterface_ValidateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_ValidateOrder_Call) Return(b bool) *MockOrderServiceInterface_ValidateOrder_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOrderServiceInterface_ValidateOrder_Call) RunAndReturn(run func(number string) bool) *MockOrderServiceInterface_ValidateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) AddUser(user model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserServiceInterface_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockUserServiceInterface_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - user model.User
func (_e *MockUserServiceInterface_Expecter) AddUser(user interface{}) *MockUserServiceInterface_AddUser_Call {
	return &MockUserServiceInterface_AddUser_Call{Call: _e.mock.On("AddUser", user)}
}

func (_c *MockUserServiceInterface_AddUser_Call) Run(run func(user model.User)) *MockUserServiceInterface_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.User
		if args[0] != nil {
			arg0 = args[0].(model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_AddUser_Call) Return(err error) *MockUserServiceInterface_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserServiceInterface_AddUser_Call) RunAndReturn(run func(user model.User) error) *MockUserServiceInterface_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) GetUser(login string) (*model.User, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserServiceInterface_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - login string
func (_e *MockUserServiceInterface_Expecter) GetUser(login interface{}) *MockUserServiceInterface_GetUser_Call {
	return &MockUserServiceInterface_GetUser_Call{Call: _e.mock.On("GetUser", login)}
}

func (_c *MockUserServiceInterface_GetUser_Call) Run(run func(login string)) *MockUserServiceInterface_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_GetUser_Call) Return(user *model.User, err error) *MockUserServiceInterface_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserServiceInterface_GetUser_Call) RunAndReturn(run func(login string) (*model.User, error)) *MockUserServiceInterface_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) ValidateUser(user model.User) (bool, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.User) (bool, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(model.User) bool); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserServiceInterface_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type MockUserServiceInterface_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - user model.User
func (_e *MockUserServiceInterface_Expecter) ValidateUser(user interface{}) *MockUserServiceInterface_ValidateUser_Call {
	return &MockUserServiceInterface_ValidateUser_Call{Call: _e.mock.On("ValidateUser", user)}
}

func (_c *MockUserServiceInterface_ValidateUser_Call) Run(run func(user model.User)) *MockUserServiceInterface_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.User
		if args[0] != nil {
			arg0 = args[0].(model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_ValidateUser_Call) Return(b bool, err error) *MockUserServiceInterface_ValidateUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserServiceInterface_ValidateUser_Call) RunAndReturn(run func(user model.User) (bool, error)) *MockUserServiceInterface_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithdrawServiceInterface creates a new instance of MockWithdrawServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithdrawServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithdrawServiceInterface {
	mock := &MockWithdrawServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWithdrawServiceInterface is an autogenerated mock type for the WithdrawServiceInterface type
type MockWithdrawServiceInterface struct {
	mock.Mock
}

type MockWithdrawServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithdrawServiceInterface) EXPECT() *MockWithdrawServiceInterface_Expecter {
	return &MockWithdrawServiceInterface_Expecter{mock: &_m.Mock}
}

// AddWithdraw provides a mock function for the type MockWithdrawServiceInterface
func (_mock *MockWithdrawServiceInterface) AddWithdraw(withdraw model.Withdraw) error {
	ret := _mock.Called(withdraw)

	if len(ret) == 0 {
		panic("no return value specified for AddWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.Withdraw) error); ok {
		r0 = returnFunc(withdraw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWithdrawServiceInterface_AddWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWithdraw'
type MockWithdrawServiceInterface_AddWithdraw_Call struct {
	*mock.Call
}

// AddWithdraw is a helper method to define mock.On call
//   - withdraw model.Withdraw
func (_e *MockWithdrawServiceInterface_Expecter) AddWithdraw(withdraw interface{}) *MockWithdrawServiceInterface_AddWithdraw_Call {
	return &MockWithdrawServiceInterface_AddWithdraw_Call{Call: _e.mock.On("AddWithdraw", withdraw)}
}

func (_c *MockWithdrawServiceInterface_AddWithdraw_Call) Run(run func(withdraw model.Withdraw)) *MockWithdrawServiceInterface_AddWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Withdraw
		if args[0] != nil {
			arg0 = args[0].(model.Withdraw)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWithdrawServiceInterface_AddWithdraw_Call) Return(err error) *MockWithdrawServiceInterface_AddWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWithdrawServiceInterface_AddWithdraw_Call) RunAndReturn(run func(withdraw model.Withdraw) error) *MockWithdrawServiceInterface_AddWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdraws provides a mock function for the type MockWithdrawServiceInterface
func (_mock *MockWithdrawServiceInterface) GetWithdraws(login string) ([]*model.Withdraw, error) {
	ret := _mock.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdraws")
	}

	var r0 []*model.Withdraw
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*model.Withdraw, error)); ok {
		return returnFunc(login)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*model.Withdraw); ok {
		r0 = returnFunc(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdraw)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWithdrawServiceInterface_GetWithdraws_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdraws'
type MockWithdrawServiceInterface_GetWithdraws_Call struct {
	*mock.Call
}

// GetWithdraws is a helper method to define mock.On call
//   - login string
func (_e *MockWithdrawServiceInterface_Expecter) GetWithdraws(login interface{}) *MockWithdrawServiceInterface_GetWithdraws_Call {
	return &MockWithdrawServiceInterface_GetWithdraws_Call{Call: _e.mock.On("GetWithdraws", login)}
}

func (_c *MockWithdrawServiceInterface_GetWithdraws_Call) Run(run func(login string)) *MockWithdrawServiceInterface_GetWithdraws_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWithdrawServiceInterface_GetWithdraws_Call) Return(withdraws []*model.Withdraw, err error) *MockWithdrawServiceInterface_GetWithdraws_Call {
	_c.Call.Return(withdraws, err)
	return _c
}

func (_c *MockWithdrawServiceInterface_GetWithdraws_Call) RunAndReturn(run func(login string) ([]*model.Withdraw, error)) *MockWithdrawServiceInterface_GetWithdraws_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateOrder provides a mock function for the type MockWithdrawServiceInterface
func (_mock *MockWithdrawServiceInterface) ValidateOrder(number string) bool {
	ret := _mock.Called(number)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOrder")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(number)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockWithdrawServiceInterface_ValidateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateOrder'
type MockWithdrawServiceInterface_ValidateOrder_Call struct {
	*mock.Call
}

// ValidateOrder is a helper method to define mock.On call
//   - number string
func (_e *MockWithdrawServiceInterface_Expecter) ValidateOrder(number interface{}) *MockWithdrawServiceInterface_ValidateOrder_Call {
	return &MockWithdrawServiceInterface_ValidateOrder_Call{Call: _e.mock.On("ValidateOrder", number)}
}

func (_c *MockWithdrawServiceInterface_ValidateOrder_Call) Run(run func(number string)) *MockWithdrawServiceInterface_ValidateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWithdrawServiceInterface_ValidateOrder_Call) Return(b bool) *MockWithdrawServiceInterface_ValidateOrder_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockWithdrawServiceInterface_ValidateOrder_Call) RunAndReturn(run func(number string) bool) *MockWithdrawServiceInterface_ValidateOrder_Call {
	_c.Call.Return(run)
	return _c
}
